### ISSUE TITLE
Правки по ЛР 1

### ISSUE THREAD

**Issue by BakasaRus** [Erartria/web_6sem#1]
- В `header` появился лишний `div`;
- `position: absolute` ломает кнопку с геолокацией;
![Screenshot_20210319_182328](https://user-images.githubusercontent.com/21131366/111803587-39e08780-88e0-11eb-94e3-33d82a75ae1f.png)
- Съезжающее название города;
![Screenshot_20210319_182353](https://user-images.githubusercontent.com/21131366/111803647-48c73a00-88e0-11eb-9b36-12bd4808db7f.png)
- Лишняя полоска под карточками (зачем?);
- Избранное лучше отделить от карточек ещё б**о**льшим отступом;
- `margin` для "Избранное" и `position: absolute` для формы - некруто, есть же flexbox.

Может, ещё что найду :smirk:

**Comment by Erartria** [comment]
1. Удалил из `header` ненужный `div` 
![image](https://user-images.githubusercontent.com/67651912/111826078-4de4b300-88f9-11eb-8d94-26aab90c4061.png)
2. Удалил параметр `position` у `header`, теперь все выглядит хорошо
![image](https://user-images.githubusercontent.com/67651912/111826382-ad42c300-88f9-11eb-8e6b-ca7f80fe31e6.png)
Вот так выглядит css для всего `header`-а
![image](https://user-images.githubusercontent.com/67651912/111826500-cd728200-88f9-11eb-87b5-7007769d0e56.png)
3. Теперь название города не съезжает:
![image](https://user-images.githubusercontent.com/67651912/111826627-f98e0300-88f9-11eb-9481-cdc41bec5c65.png)
*Это при минимально возможном расширении 150px x 788px
4. Полоска была добавлена для разнообразия - я так это вижу. Прислушавшись к Вам, убрал её:
![image](https://user-images.githubusercontent.com/67651912/111826981-66a19880-88fa-11eb-8d88-9282277a46e1.png)
5. Увеличил отступ между секцией `добавления городов` и секцией, содержащей `карточки добавленных городов`:
![image](https://user-images.githubusercontent.com/67651912/111827112-92248300-88fa-11eb-84a4-b2bf3ddbb9e8.png)
6. Переписал секцию "избранное" без `margin`-ов и `position:absolute`:
![image](https://user-images.githubusercontent.com/67651912/111827291-c6983f00-88fa-11eb-980a-fee461b9c844.png)
